# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PoligonizadorLinhaCorte
                                 A QGIS plugin
 Plugin para poligonizar linhas de corte e gerar lotes automaticamente
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-10
        copyright            : (C) 2025 by Geotecnologia
        email                : Geotecnologia@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PoligonizadorLinhaCorte class from file PoligonizadorLinhaCorte.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .poligonizador_linha_corte import PoligonizadorLinhaCorte
    return PoligonizadorLinhaCorte(iface)
